/**
 * @fileoverview gRPC-Web generated client stub for wav2LipApi
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.19.4
// source: message.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as message_pb from './message_pb';


export class Wav2LipApiServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorwav2lipApi = new grpcWeb.MethodDescriptor(
    '/wav2LipApi.Wav2LipApiService/wav2lipApi',
    grpcWeb.MethodType.SERVER_STREAMING,
    message_pb.TalkConfigRequest,
    message_pb.StreamMessage,
    (request: message_pb.TalkConfigRequest) => {
      return request.serializeBinary();
    },
    message_pb.StreamMessage.deserializeBinary
  );

  wav2lipApi(
    request: message_pb.TalkConfigRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<message_pb.StreamMessage> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/wav2LipApi.Wav2LipApiService/wav2lipApi',
      request,
      metadata || {},
      this.methodDescriptorwav2lipApi);
  }

}

